import { Link } from "react-router-dom";
import SiteFooter from "@/components/SiteFooter";
import Seo from "@/components/Seo";

const Terms = () => (
  <div className="min-h-screen bg-background text-foreground">
    <Seo
      title="Terms of Service — Comment Decoder Pro"
      description="The terms for using Comment Decoder Pro: acceptable use, third-party content, AI-generated output, availability and liability."
      path="/terms"
    />
    <main className="max-w-3xl mx-auto px-4 py-12">
      <nav className="mb-8 text-sm">
        <Link to="/" className="text-primary hover:underline">← Back to app</Link>
      </nav>
      <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: May 25, 2026</p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">1. Acceptance</h2>
      <p className="mb-6">
        By using Comment Decoder Pro you agree to these Terms. If you do not agree,
        please do not use the service.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">2. The service</h2>
      <p className="mb-6">
        Comment Decoder Pro is a free tool that analyzes the public comments of
        YouTube videos using AI. Results are estimates and are provided "as is" with
        no warranty of accuracy or fitness for any particular purpose.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">3. Acceptable use</h2>
      <ul className="list-disc pl-6 space-y-2 mb-6">
        <li>Do not use the service to harass, dox, or harm any commenter</li>
        <li>Do not attempt to overload, scrape, or reverse-engineer the service</li>
        <li>Do not republish results in a way that misrepresents individual commenters</li>
        <li>Respect YouTube's own Terms of Service when using data fetched here</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-3">4. Third-party content</h2>
      <p className="mb-6">
        Comments shown in the app belong to their authors and are fetched from the
        public YouTube Data API. We do not claim ownership of any comment content.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">5. AI-generated output</h2>
      <p className="mb-6">
        Sentiment scores, summaries, content ideas, and suggested replies are
        generated by AI models and may contain errors. Always review before publishing
        or acting on the output.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">6. Availability</h2>
      <p className="mb-6">
        The service is provided free of charge and may be modified, rate-limited, or
        discontinued at any time without notice.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">7. Limitation of liability</h2>
      <p className="mb-6">
        To the maximum extent permitted by law, we are not liable for any indirect,
        incidental, or consequential damages arising from your use of the service.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">8. Changes</h2>
      <p>
        We may update these Terms from time to time. Continued use of the service
        after a change constitutes acceptance of the new Terms.
      </p>
    </main>
    <SiteFooter />
  </div>
);

export default Terms;
